### ISSUE TITLE
Scraping with Phantomjs

### ISSUE THREAD

**Issue by DZGoldman** [DZGoldman/Scraper#1]
@WilliamfShaw @jasonseminara @zhenpanda @amcooper 

Hi, I have a question about web-scraping. This is a side-repo, separate from our main project repo.

I'm attempting to scrape the resumes off of this page:

http://www.super-resume.com/ResumeBuilder.jtp?query=Computer+Programmer

using the Phantom node module of Phantomjs, a headless browser program. 

I realize that this question may be a bit too arcane and specific to get help with, but I thought I may as well try. 

Ignore the master branch for now; the scrapesingle branch (headlessly) opens this link:
http://www.super-resume.com/ResumeBuilder.jtp?query=Computer+Programmer
then grabs resume link from the sidebar (a different link for whatever number you feed it, 1 through 20) and successfully scrapes that resume and sends the result to the browser at '/'. 

That's all well and good, but the real goal is to scrape many resumes at once. On the looping branch, instead of just grabbing one link, it grabs all 20 (successfully). The idea is to then loop through all 20 links with a forEach loop and essentially, one by one, preform the same scraping operation that was preformed on the scrape-single branch.

This isn't working. I think the logic itself is sound, but I've gathered that the problem is probably a-synchronicity; it takes time for each resume page to load, but the javascript keeps running and moves on to the next resume before the last one is done. 

A lot of the suggestions I've found online involve using CasperJs, which runs on top of Phantomjs, but I'd rather not have to download another program since Phantomjs was very hard to configure and learn to use.

Other suggestions involve nesting each link deeper in a call-back. But this, aside from just being generally terrible, isn't really a solution, since the idea is to create an app that can scrape literally any number of links on any page on this site, not just one list that the programmer haplessly and pathetically feeds it. 

 I've thought about reconfiguring it with a recursive function instead of a forEach loop, but I'm worried that may just be just as asynchronous. 

Any suggestions — even just pointing in the general direction of research avenues to pursue — would be appreciated.
Thanks.

**Comment by WilliamfShaw** [comment]
@DZGoldman Has there been any resolve to this?

**Comment by WilliamfShaw** [comment]
So the idea I think you are looking for it to arbitrarily parse information and then have your program make sense of it. I think @jasonseminara would be the person to speak with here.

**Comment by DZGoldman** [comment]
I used Casper to successfully grab lots of data (traversing to many links and such). I have it as an array of objects. Now the question is how to save it as a JSON or something similar. Ideally I could just use a router to send it to page and then just save the page from the browser, but Casper can't be used inside of a node ap.
